#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/board
#spring.datasource.username=root
#spring.datasource.password=1111
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#
#spring.data.redis.host=localhost
#spring.data.redis.port=6379

spring:
  profiles:
      active:
        dev
